version: '3.8'

services:
  edumanage-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edumanage-backend-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - JWT_SECRET=super_secret_key_edumanage_2026_key
      - DATA_PATH=/app/data_store/db_data.json
    volumes:
      - ./data_store:/app/data_store
